# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8.2"

  config.vm.provision "shell", inline: <<-SHELL
    PROVII_SRC=/vagrant/provii/provii
    PROVII_DST=/usr/bin/provii
    USER=vagrant

    ## PROVII_URL=https://raw.githubusercontent.com/l0xy/provii/master/provii
    ## curl -sSLo $PROVII_PATH $PROVII_URL

    cp $PROVII_SRC $PROVII_DST
    chmod 755 $PROVII_DST

    yum install -y zsh util-linux-user
    echo '. /etc/zshrc' > /home/$USER/.zshrc
    chsh -s `which zsh` $USER

    curl -fsSL https://starship.rs/install.sh | bash -s -- -f
    echo 'eval "$(starship init zsh)"' >> /home/$USER/.zshrc

    yum install -y tmux 
    yum install -y vim
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y bats
    /vagrant/provii/tests/provii.bats
  SHELL
end
