#!/usr/bin/env bash

# bandwidth utilization tool for the terminal
# https://github.com/imsnif/bandwhich

ASSET_RE=$( printf '%s.*%s.*%s' $NAME $ARCH $OS )

github imsnif/bandwhich "${NAME}.*${ARCH}.*${OS}"
tar -xf ./* 

install bandwhich
