#!/usr/bin/env bash

# bandwidth utilization tool for the terminal
# https://github.com/imsnif/bandwhich

github imsnif/bandwhich .*-$(uname -m)-unknown-linux-musl\.tar\.gz$
tar -xf ./* 

install bandwhich
