#!/usr/bin/env bash

# a cat clone with wings
# https://github.com/sharkdp/bat

github sharkdp/bat "$ARCH.*$OS.*$LIBC.*gz"
tar -xf ./* --strip=1

install bat

if [ $MAN ]; then
	cp bat.1 $MAN/man1
fi
