#!/usr/bin/env bash

# hex-editor, inspired by vi
# http://bvi.sourceforge.net/

URL_FQDN='prdownloads.sourceforge.net'
URL_DIR='bvi'
URL_FILE='bvi-1.3.1-linux_static_elf.tar.gz'

printf -v FULL_URL 'https://%s/%s/%s' \
    "$URL_FQDN" "$URL_DIR" "$URL_FILE"

curl -#L $FULL_URL | tar -xzf - --strip=1

install bvi
install bmore


