#!/usr/bin/env bash

# hex-editor, inspired by vi
# http://bvi.sourceforge.net/

URL_FQDN='prdownloads.sourceforge.net'
URL_DIRS='bvi'
URL_FILE='bvi-1.3.1-linux_static_elf.tar.gz'

URL=$(printf 'https://%s/%s/%s' $URL_{FQDN,DIRS,FILE})
curl -#L $URL | tar -xzf - --strip=1

install bvi
cp bvi.man $MAN/man1/

install bmore
cp bmore.man $MAN/man1/


