#!/usr/bin/env bash

# a simple, fast and user-friendly alternative to find
# https://github.com/sharkdp/fd

github sharkdp/fd "$ARCH.*$OS.*$LIBC.*gz$"
tar -xf ./* --strip=1 

install fd $BIN/

if [ $MAN ]; then
	cp fd.1 $MAN/man1/fd.1
fi
if [ $ZSH_COMP ]; then
	cp autocomplete/_fd $ZSH_COMP/
fi
if [ $BASH_COMP ]; then
	cp autocomplete/fd.bash-completion $BASH_COMP/
fi
