#!/usr/bin/env bash

# terminal JSON viewer
# https://fx.wtf

FILE_RE=$( printf '%s.*%s' $NAME $OS )
github antonmedv/fx $FILE_RE
unzip ./*
install fx-$OS $BIN/fx

[ $BASH_COMP ] \
	&& github antonmedv/fx-completion/complete.sh \
	&& cp complete.sh $BASH_COMP/fx.bash-completion
