#!/usr/bin/env bash

# terminal JSON viewer
# https://fx.wtf

github antonmedv/fx "$NAME.*$OS"
unzip -d bin/ ./* >/dev/null

install bin/fx* $BIN/fx

if [ $BASH_COMP ]; then
	github antonmedv/fx-completion/complete.sh
	cp complete.sh $BASH_COMP/fx.bash-completion
fi
