#!/usr/bin/env bash

# a command-line fuzzy finder
# https://github.com/junegunn/fzf

github junegunn/fzf-bin "$NAME.*$OS.*$ARCH"
tar -xf ./*

install fzf

if [ $MAN ]; then
	github junegunn/fzf/man/man1/fzf.1
	cp man/man1/fzf.1 $MAN/man1/
fi
if [ $BASH_COMP ]; then
	github junegunn/fzf/shell/completion.bash
	cp shell/completion.bash $BASH_COMP/$NAME.bash-completion
fi
if [ $ZSH_COMP ]; then
	github junegunn/fzf/shell/completion.zsh
	cp shell/completion.zsh $ZSH_COMP/_$NAME
fi
