#!/usr/bin/env bash

# a command-line fuzzy finder
# https://github.com/junegunn/fzf

github junegunn/fzf-bin "$NAME.*$OS.*$ARCH"
tar -xf ./*

install fzf

[ $BASH_COMP ] \
	&& github junegunn/fzf/shell/completion.bash \
	&& cp completion.bash $BASH_COMP/$NAME.completion.bash

[ $ZSH_COMP ] \
	&& github junegunn/fzf/shell/completion.zsh \
	&& cp completion.zsh $ZSH_COMP/_$NAME

[ $MAN ] \
	&& github junegunn/fzf/man/man1/fzf.1 \
	&& cp fzf.1 $MAN/man1/
