#!/usr/bin/env bash

# GitHub’s official command line tool
# https://cli.github.com

github cli/cli "$OS.*$ARCH.*gz$"
tar -xf ./* --strip=1

install bin/gh

if [ $MAN ]; then
	cp share/man/man1/* $MAN/man1/
fi
