#!/usr/bin/env bash

# render markdown on the CLI, with pizzazz!
# https://github.com/charmbracelet/glow

FILE_RE='.*linux.*x86_64.*gz$'
github charmbracelet/glow "$FILE_RE"
tar -xf ./*

install glow
