#!/usr/bin/env bash

# command-line JSON processor
# https://stedolan.github.io/jq/

case $(uname -m) in
	*64) ARCH=64 ;;
	*) ARCH=32 ;;
esac

github stedolan/jq "$NAME.*$OS.*$ARCH"
install jq* $BIN/jq
