#!/usr/bin/env bash

# linux kernel manager and activity monitor
# https://kmon.cli.rs/

ASSET_RE=$( printf '%s.*gz$' $NAME )
github orhun/kmon $ASSET_RE
tar -xf ./*

install kmon
[ $MAN ] && cp man/kmon.8 $MAN/man8/
