#!/usr/bin/env bash

# linux kernel manager and activity monitor
# https://kmon.cli.rs/

github orhun/kmon "$NAME.*$LIBC.*gz$"
tar --strip=1 -xf ./*

install kmon $BIN/

if [ $MAN ]; then
	cp man/kmon.8 $MAN/man8/
fi
