#!/usr/bin/env bash

# ls(deluxe) - the next gen ls command
# https://github.com/Peltoche/lsd

FILE_RE='%s.*%s.*%s.*(gnu)?.*gz$' $NAME $ARCH $OS
github Peltoche/lsd "$FILE_RE"
tar -xf ./* --strip=1

install lsd

[ $BASH_COMP ] \
	&& cp autocomplete/lsd.bash-completion $BASH_COMP/

[ $ZSH_COMP ] \
	&& cp autocomplete/_lsd $ZSH_COMP/
