#!/usr/bin/env bash

# ls(deluxe) - the next gen ls command
# https://github.com/Peltoche/lsd

github Peltoche/lsd "$NAME.*$ARCH.*$OS.*$LIBC.*gz$"
tar -xf ./* --strip=1 

install lsd $BIN/

if [ $BASH_COMP ]; then
	cp autocomplete/lsd.bash-completion $BASH_COMP/
fi
if [ $ZSH_COMP ]; then
	cp autocomplete/_lsd $ZSH_COMP/
fi
