#!/usr/bin/env bash

# render md files in your terimanal, offers both cat-like and pager-like functionality
# https://github.com/lunaryorn/mdcat

github lunaryorn/mdcat '.*linux.*musl.*gz'
tar -xf ./* --strip=1

install mdcat \
	&& ln $BIN/mdcat $BIN/mdless
cp completions/mdcat.bash $BASH_COMPLETIONS/
