#!/usr/bin/env bash

# render md files in your terimanal, offers both cat-like and pager-like functionality
# https://github.com/lunaryorn/mdcat

github lunaryorn/mdcat "$NAME.*$OS"
tar -xf ./* --strip=1

install mdcat $BIN/mdcat
install mdcat $BIN/mdless

if [ $BASH_COMP ]; then
	cp completions/mdcat.bash $BASH_COMP/mdcat.bash-completion
fi
if [ $ZSH_COMP ]; then
	cp completions/_mdcat $ZSH_COMP/
fi
