#!/usr/bin/env bash

# interactive cheatsheet tool for the command-line
# https://github.com/denisidoro/navi

FILE_RE='^.*-unknown-linux-musl.*gz$'
github denisidoro/navi "$FILE_RE" 
tar -xf ./*

install navi
