#!/usr/bin/env bash

# recursively search directories for a regex pattern
# https://github.com/BurntSushi/ripgrep

github BurntSushi/ripgrep "$ARCH.*$OS"
tar -xzf ./* --strip=1

install rg

[ $MAN ] \
	&& cp doc/rg.1 $MAN/man1/ 
[ $BASH_COMP ] \
	&& cp complete/rg.bash $BASH_COMP/rg.bash-completion
[ $ZSH_COMP ] \
	&& cp complete/_rg $ZSH_COMP/
