#!/usr/bin/env bash

# a shell script static analysis tool
# https://github.com/koalaman/shellcheck

ASSET_RE=$( printf '%s.*%s.*xz$' $OS $ARCH )
github koalaman/shellcheck $ASSET_RE
tar -xJf ./*

install shellcheck
