#!/usr/bin/env bash

# universal command-line interface for SQL databases
# https://github.com/xo/usql

ASSET_RE=$( printf '%s.*%s.*%s' $NAME $OS $ARCH )
github xo/usql $ASSET_RE
tar -xjf ./* usql

install usql

