#!/usr/bin/env bash

# a cat clone with wings
# https://github.com/sharkdp/bat

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github sharkdp/bat "$ARCH_RE.*$OS_RE.*${LIBC:-}.*gz$"
tar -xf ./* --strip=1

install bat $BIN/

if [ $MAN ]; then
	cp bat.1 $MAN/man1
fi
