#!/usr/bin/env bash

# easily and securely send things from one computer to another
# https://github.com/schollz/croc

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github schollz/croc "$OS_RE.*$ARCH_RE.*tar.gz$"
tar xf ./* croc

install croc $BIN/
