#!/usr/bin/env bash

# style & format diff output for easy reading
# https://github.com/dandavison/delta

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github dandavison/delta "$ARCH_RE.*$OS_RE.*${LIBC:-}.*gz$"
tar -xf ./* --strip=1

install delta $BIN/
