#!/usr/bin/env bash

# a tool for exploring each layer in a docker image 
# https://github.com/wagoodman/dive

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github wagoodman/dive "$OS_RE.*$ARCH_RE.*gz$"
tar -xf ./*

install dive $BIN/
