#!/usr/bin/env bash

# a more intuitive version of du in rust
# https://github.com/bootandy/dust

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github bootandy/dust "$NAME.*$ARCH_RE.*$OS_RE.*${LIBC:-}.*gz$"
tar -xf ./* --strip=1

install dust $BIN/
