#!/usr/bin/env bash

# a modern version of ls
# https://the.exa.website

ARCH_RE="$(asset_arch_re)"
case "$OS" in
darwin)
	github ogham/exa "$NAME.*macos.*$ARCH_RE.*zip$"
	;;
*)
	github ogham/exa "$NAME.*$OS.*$ARCH.*-musl"
	;;
esac
unzip ./* -d output/ 1>/dev/null
cd output

install bin/exa* $BIN/exa

if [ $BASH_COMP ]; then
	cp completions/exa.bash $BASH_COMP/exa.bash-completions
fi

if [ $ZSH_COMP ]; then
	cp completions/exa.zsh $ZSH_COMP/_exa
fi

if [ $MAN ]; then
	cp man/exa.1 $MAN/man1/
 	cp man/exa_colors.5 $MAN/man5/
fi
