#!/usr/bin/env bash

# terminal JSON viewer
# https://fx.wtf

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github antonmedv/fx "$NAME.*$OS_RE.*$ARCH_RE$"

install fx* $BIN/fx

if [ $BASH_COMP ]; then
	github antonmedv/fx-completion/complete.sh
	cp complete.sh $BASH_COMP/fx.bash-completion
fi
