#!/usr/bin/env bash

# a command-line fuzzy finder
# https://github.com/junegunn/fzf

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github junegunn/fzf "$NAME.*$OS_RE.*$ARCH_RE.*(tgz|tar.gz)$"
tar -xf ./*

install fzf $BIN/

if [ $MAN ]; then
	github junegunn/fzf/man/man1/fzf.1
	cp man/man1/fzf.1 $MAN/man1/
fi
if [ $BASH_COMP ]; then
	github junegunn/fzf/shell/completion.bash
	cp shell/completion.bash $BASH_COMP/$NAME.bash-completion
fi
if [ $ZSH_COMP ]; then
	github junegunn/fzf/shell/completion.zsh
	cp shell/completion.zsh $ZSH_COMP/_$NAME
fi
