#!/usr/bin/env bash

# command-line JSON processor
# https://stedolan.github.io/jq/

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github stedolan/jq "$NAME.*$OS_RE.*$ARCH_RE$"
install jq* $BIN/jq
