#!/usr/bin/env bash

# ls(deluxe) - the next gen ls command
# https://github.com/Peltoche/lsd

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github Peltoche/lsd "$NAME.*$ARCH_RE.*$OS_RE.*${LIBC:-}.*gz$"
tar -xf ./* --strip=1 

install lsd $BIN/

if [ $BASH_COMP ]; then
	cp autocomplete/lsd.bash-completion $BASH_COMP/
fi
if [ $ZSH_COMP ]; then
	cp autocomplete/_lsd $ZSH_COMP/
fi
