#!/usr/bin/env bash

# recursively search directories for a regex pattern
# https://github.com/BurntSushi/ripgrep

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
case "$OS:$ARCH" in
linux:x86_64 | linux:amd64)
	github BurntSushi/ripgrep "x86_64.*$OS_RE.*tar.gz$"
	;;
*)
	github BurntSushi/ripgrep "$ARCH_RE.*$OS_RE.*${LIBC:-}.*tar.gz$"
	;;
esac
tar -xzf ./* --strip=1

install rg $BIN/

if [ $MAN ]; then
	cp doc/rg.1 $MAN/man1/ 
fi
if [ $BASH_COMP ]; then
	cp complete/rg.bash $BASH_COMP/rg.bash-completion
fi
if [ $ZSH_COMP ]; then
	cp complete/_rg $ZSH_COMP/
fi
