#!/usr/bin/env bash

# a shell script static analysis tool
# https://github.com/koalaman/shellcheck

ARCH_RE="$(asset_arch_re)"
OS_RE="$(asset_os_re)"
github koalaman/shellcheck "$OS_RE.*$ARCH_RE.*xz$"
tar -xJf ./* --strip=1 

install shellcheck $BIN/
