#!/usr/bin/env bash

# a tool for writing interactively crafting linux pipes,
# with instant live preview of command results
# https://github.com/akavel/up

case "$OS" in
darwin) github akavel/up "^$NAME-darwin$" ;;
*) github akavel/up "^$NAME$" ;;
esac
install up $BIN/
