name: DigitalOcean Spaces Action
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Sync DigitalOcean Spac, purge changes from the CDN
        uses: laukstein/do-spaces@main
        env:
          DO_ACCESS: ${{ secrets.SPACE_ACCESS_KEY }}
          DO_SECRET: ${{ secrets.SPACE_SECRET_KEY }}
          DO_NAME: ${{ secrets.SPACE_NAME }}
          DO_REGION: ams3
          DO_DIR: provii/latest
          LOCAL_DIR: src
