name: CDN Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nebula-dev/spaces-sync-action@v1.0.0
      env:
        SOURCE_DIR: './src/'
        SPACE_REGION: 'nyc3'
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
        SPACE_ACCESS_KEY: ${{ secrets.SPACE_ACCESS_KEY }}
        SPACE_SECRET_KEY: ${{ secrets.SPACE_SECRET_KEY }}
