#!/usr/bin/env bash

# command-line benchmarking utility
# https://github.com/sharkdp/hyperfine

github sharkdp/hyperfine "$ARCH.*$OS.*$LIBC.*gz"
tar -xf ./* --strip=1

install hyperfine $BIN/

if [ $MAN ]; then
	cp hyperfine.1 $MAN/man1
fi
if [ $BASH_COMP ]; then
	cp autocomplete/hyperfine.bash $BASH_COMP/hyperfine.bash-completion
fi
if [ $ZSH_COMP ]; then
	cp autocomplete/_hyperfine $ZSH_COMP/
fi
