#!/bin/bash

# robust cli image viewing / manipulation tool
# https://imagemagick.org

URL_FQDN='imagemagick.org'
URL_DIRS='/download/binaries/'
URL_FILE='magick'

URL=$(printf 'https://%s/%s/%s' $URL_{FQDN,DIRS,FILE})
curl -#LO $URL

install magick $BIN/
